### ISSUE TITLE
Support conditional chain operator (?.)

### ISSUE THREAD

**Issue by maclockard** [lukastaegert/eslint-plugin-tree-shaking#88]
Currently get this stack trace when calling a function with a conditional chain operator upon initialization:
```
[Error - 10:22:26 PM] TypeError: Cannot read property 'hasValue' of undefined
Occurred while linting /Users/maclockard/workspace/hex-inc/hex/packages/client/components/markdown/MarkdownSanitizeSchema.ts:2
    at Object.|| (/Users/maclockard/workspace/hex-inc/hex/node_modules/eslint-plugin-tree-shaking/lib/rules/no-side-effects-in-initialization.js:152:22)
    at Object.getValueAndReportEffects (/Users/maclockard/workspace/hex-inc/hex/node_modules/eslint-plugin-tree-shaking/lib/rules/no-side-effects-in-initialization.js:663:48)
    at reportSideEffects (/Users/maclockard/workspace/hex-inc/hex/node_modules/eslint-plugin-tree-shaking/lib/rules/no-side-effects-in-initialization.js:907:24)
    at /Users/maclockard/workspace/hex-inc/hex/node_modules/eslint-plugin-tree-shaking/lib/rules/no-side-effects-in-initialization.js:256:43
    at Array.forEach (<anonymous>)
    at Object.reportEffects (/Users/maclockard/workspace/hex-inc/hex/node_modules/eslint-plugin-tree-shaking/lib/rules/no-side-effects-in-initialization.js:256:24)
    at reportSideEffects (/Users/maclockard/workspace/hex-inc/hex/node_modules/eslint-plugin-tree-shaking/lib/rules/no-side-effects-in-initialization.js:905:24)
    at /Users/maclockard/workspace/hex-inc/hex/node_modules/eslint-plugin-tree-shaking/lib/rules/no-side-effects-in-initialization.js:734:11
    at Array.forEach (<anonymous>)
    at Object.reportEffects (/Users/maclockard/workspace/hex-inc/hex/node_modules/eslint-plugin-tree-shaking/lib/rules/no-side-effects-in-initialization.js:732:25)
```

**Comment by thorsent** [comment]
+1

**Comment by lukastaegert** [comment]
PR welcome
